G-Research/consuldotnet

Consul.Test/Properties/AssemblyInfo.cs
This will make the release process simpler.
=> Do not set a version for the unit tests

.github/workflows/ci.yml
=> Fix incorrect merge of assemblies

.github/workflows/ISSUE_TEMPLATE/bug_report.md
=> github: add bug report template

Consul/Agent.cs
Add https://www.consul.io/api-docs/agent/check#grpc and https://www.consul.io/api-docs/agent/check#grpcusetls agent check settings
=> Add GRPC and GRPCUseTLS agent check settings

Consul.AspNetCore.Test/Consul.AspNetCore.Test.csproj, Consul.AspNetCore.Test/ConsulClientFactoryTests.cs, Consul.AspNetCore.Test/ConsulOptionsTestHelper.cs, Consul.AspNetCore.Test/ServiceCollectionExtensionsTest.cs, Consul.AspNetCore/Consul.AspNetCore.csproj, Consul.AspNetCore/ConsulClientFactory.cs, Consul.AspNetCore/IConsulClientFactory.cs, Consul.AspNetCore/ServiceCollectionExtensions.cs, Consul/Client.cs
More info here https://github.com/G-Research/consuldotnet/pull/38
Merged new asp net core integration, tests and remove obsolete
=> Add asp net core integration V2

.github/workflows/ci.yml, .github/workflows/consul.aspnetcore.yml, Consul/Consul.csproj
https://github.com/G-Research/consuldotnet/pull/38
=> Add AspNetCore CI

Consul.Test/FilterTests.cs, Consul/Client_GetRequests.cs, Consul/Health.cs
https://github.com/G-Research/consuldotnet/pull/70 introduced some ABI breaking changes, this PR aims to fix that.
=> Improving ABI compatibility

.github/workflows/ci.yml
This PR updates the versions of Consul used for testing to the current latest versions.
=> Update versions of Consul used for testing

Consul.Test/KVTest.cs
I checked for others and this is the last test using that unreliable timing mechanism to validate the test.
=> test: fix another intermittently failing test

.github/workflows/ci.yml
This PR updates the versions of Consul agent used for testing to the newly released ones.
=> Update Consul agent versions used for testing

CHANGELOG.md, Directory.Build.props, README.md
=> Update changelog and release process

Consul.Test/BaseFixture.cs, Consul.Test/Properties/AssemblyInfo.cs, Consul.Test/SessionTest.cs, Consul/Session.cs, README.md
Test `Session_Create_RenewPeriodic_TTLExpire` was failing quite often, that problem should be fixed now.
=> Fix the flakiness of Session_Create_RenewPeriodic_TTLExpire

README.md
I resized the logo image and aligned it left to standardize visually with the other projects.
=> Resized logo and aligned left

CHANGELOG.md, Directory.Build.props
I updated the version number to be able to create the release for nuget as I need the Filters on the `Agent.Services` 
Thanks.
=> update versions to trigger the build

.github/workflows/ci.yml, Consul.Test/ACLTest.cs
Add support for testing against Consul agent 1.11.x.
=> Test with Consul 1.11.x

CHANGELOG.md
I would like to create a new release since we have fixed an issue that was blocking one of the users.
=> Update the change log for next release

docs/docs/3-contributing/6-release-process.mdx
Minor grammatical edit to Update 6-release-process.mdx
=> Edit grammar Update 6-release-process.mdx

.github/ISSUE_TEMPLATE/feature_request_form.yaml
Adding an issue template for requesting features, including the following inputs:
- Related problem
- Suggested solution/implementation
- Alternatives (optional)
- Additional context (optional)
=> add issue template for feature requests

CHANGELOG.md
Since we've implemented all missing features for v1.7 we should make a new release.
@winstxnhdw many thanks to you for all your hard work on getting us ready for v1.7.
=> Preparing the CHANGELOG for a new release

Directory.Build.props
Before creating the new release we also need to update the version in `Directory.Build.props`
=> Updating the version for a new release

.github/dependabot.yaml
The goal of this PR is to add DependaBot workflow 
https://github.com/G-Research/oss-portfolio-maturity/issues/278
=> CI: Add DependaBot checks

docs/src/pages/Index/Index.module.css, docs/src/pages/Index/Index.view.tsx
Fix some responsiveness issues in website:
=> Fixing Mobile Responsiveness of the Website

docs/docusaurus.config.js
Add tracking tag for Google Analytics 4
=> add Google Analytics 4

.github/workflows/ci.yml
Reverts G-Research/consuldotnet#306
=> Revert "Update Consul agent versions used for testing"

Consul.Test/ClientTest.cs
The `Client_DefaultConfig_env` modifies environment variables, so we cannot run this test in parallel with other tests.
Also, we need to make sure that the env variables are set back to their original values.
=> [Testing] Make sure the env stays unmodified

docs/docs/2-guides/3-supported-apis.mdx
Fixes https://github.com/G-Research/consuldotnet/issues/357
=> Typo in documentation

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
- Installing mono on Linux runners
- Installing .NET SDK v8.0.x for the format checker job
=> Resolving CI issues

Directory.Build.props
Bumping version after release for future nightly builds.
=> Post-release version bump

Consul.Test/ConnectTest.cs, Consul/Connect.cs, Consul/Interfaces/IConnectEndpoint.cs
This PR adds support to [List Matching Intentions](https://developer.hashicorp.com/consul/api-docs/connect/intentions#list-matching-intentions)
=>  list matching intentions

Consul.Test/ConnectTest.cs, Consul/Connect.cs, Consul/Interfaces/IConnectEndpoint.cs
This PR adds support to [Check Intention Result](https://developer.hashicorp.com/consul/api-docs/connect/intentions#check-intention-result)
=> Check intention result

docs/docs/2-guides/3-supported-apis.mdx
Update supported APIs table to reflect new changes
This PR updates the service-intentions endpoints to reflect their current status, highlighting newly supported endpoints and marking deprecated ones
=> Update supported APIs table

Consul.Test/PolicyTest.cs, Consul/Interfaces/IPolicyEndpoint.cs, Consul/Policy.cs
This PR adds supports to preview a templated policy.
Here's a reference link on the API docs: [Preview a Templated Policy](https://developer.hashicorp.com/consul/api-docs/acl/templated-policies#preview-a-templated-policy)
=> Preview a templated policy by name

Consul.Test/PolicyTest.cs, Consul/Interfaces/IPolicyEndpoint.cs, Consul/Policy.cs
This feature adds support for listing all templated policies on the server. Here's a reference to the API docs: [ListTemplatedPolices](https://developer.hashicorp.com/consul/api-docs/acl/templated-policies#list-templated-policies)
=>  list templated policies

Consul.Test/PolicyTest.cs, Consul/Interfaces/IPolicyEndpoint.cs, Consul/Policy.cs
This PR adds supports to  read a specific templated policy by name.
Link to API reference: [ReadATemplatedPolicyByName](https://developer.hashicorp.com/consul/api-docs/acl/templated-policies#read-a-templated-policy-by-name)
=> Read a templated policy by name

Consul.Test/PolicyTest.cs, Consul/Interfaces/IPolicyEndpoint.cs, Consul/Policy.cs
This PR adds support to read a policy by name.
API docs ref: [ReadAPolicyByName](https://developer.hashicorp.com/consul/api-docs/acl/policies#read-a-policy-by-name)
=> Read a policy by name
