G-Research/consuldotnet

Consul.Test/LockTest.cs
* Increases timeouts in lock tests
* Fixes exception checks to actually check an exception is thrown
* Fix tests that didn't actually test anything
* Various tidy ups to make tests more readable
I still need to look at the semaphore tests and make similar changes.
=> Tidy up lock tests and increase timeouts

Consul.Test/LockTest.cs, Consul.Test/SemaphoreTest.cs, Consul.Test/TimeoutUtils.cs
* Move timeout utils into a separate class
* Fix tests that check for exceptions being thrown
* Use longer timeouts when waiting for tasks to reduce flakiness in CI
* Fix Semaphore_ExecuteAction so it actually checks the action is executed
* Remove Semaphore_ForceInvalidate test as this wasn't actually testing anything different to Semaphore_Destroy
Contains the same changes as #4 so may need rebasing once that is merged
=> Tidy up semaphore tests

.github/workflows/ci.yml
Tests need to succeed on all platforms first, and the tag name needs to match the version number.
=> Publish NuGet package when a tag is pushed

.github/workflows/ci.yml, CHANGELOG.md, Consul.Test/Properties/AssemblyInfo.cs, Consul/Consul.csproj, Consul/Properties/AssemblyInfo.cs
* Fix NuGet push (PowerShell would not do glob expansion for the command)
* Add comments about NuGet publication in the workflow file
* Change version to 1.6.1, as 1.6.1.0 would be trimmed by NuGet
=> Fix NuGet push

.github/workflows/ci.yml, Consul.Test/Consul.Test.csproj
.NET Core 2.0 is obsolete. We will use .NET Core 2.1 instead, as it's an LTS release.
We also switch the version of .NET Core SDK to the one supplied in the Windows CI builder, as this version provides more than one runtime, allowing to test on 2.1 and 3.1 at the same time.
This PR fixes the current CI failures on Windows.
=> Update Consul.Test .NET Core targets

Consul.Test/AgentTest.cs, Consul.Test/PolicyTest.cs, Consul/Agent.cs, Consul/Policy.cs, Consul/Role.cs, Consul/Token.cs
This PR fixes a few compatibility issues with Consul 1.7.x and above (latest version is 1.8.3 at the time of writing).
- Consul 1.7 requires an existing node name for Agent.ForceLeave, breaking `Consul.Test.AgentTest.Agent_ForceLeave`
- Consul 1.7 requires a body with a JSON object for Token.Clone, breaking `Consul.Test.TokenTest.Token_ReadCloneUpdateDelete`
Also added a Clone method that allows to set the description for the new token.
- Consul 1.7 requires proper PolicyLink and RoleLink structures, breaking multiple Role and Token tests
Made PolicyEntry and RoleEntry base classes instead of subclasses of PolicyLink and RoleLink respectively.
Added implicit conversion methods from xEntry to xLink for convenience and backwards compatibility.
It also removes the useless test …
=> Compatibility with Consul 1.7.x

CHANGELOG.md, Consul/Agent.cs, Consul/Consul.csproj
Added additional Consul HTTP API parameter to detail the service check registration.
Reference to <https://www.consul.io/docs/discovery/services> and this <https://www.consul.io/docs/discovery/checks> page of Consul's documentation.
We are going to use those options to allow specify distinct host http header and host address values.
Sample definition
```csharp
new AgentServiceCheck{
HTTP = $"http://srv1.servers.contoso.com/weatherforecast",
Timeout = TimeSpan.FromMilliseconds(100),
Interval = TimeSpan.FromSeconds(1),
Header = new Dictionary<string, List<string>>{ {"Host",new List<string>{"app.contoso.com"} } },
Method = "GET",
}
```
=> Allow further service check property to be specified when registering a service

CHANGELOG.md, Consul/Consul.csproj, README.md
- Reverting the version back to the `v1.6.1.1` (The `v1.7.0` wasn't published to NuGet.org)
- Adding information to the README file about versioning and the release process of Consul.NET
=> Add information to the readme about versioning and the release process

CHANGELOG.md, Consul/Agent.cs, Consul/Health.cs
`Type` field was added to consul between  `v1.6.1` and `v1.6.9`.
=> Adding new API fields to get ready for the v1.6.9 release

CHANGELOG.md, Consul/Client.cs
This is to allow continued support for providing an external HttpClient to the ConsulClient. Closes #24
=> Remove [Obsolete] attribute for ConsulClient HttpClient constructor

.github/workflows/ci.yml, .github/workflows/consul.aspnetcore.yml
This PR fixes the path used to download the nuget artifact so it matches the one used to upload it.
This unfortunately got broken in #46.
=> Fix NuGet package publication

.github/workflows/ci.yml, .github/workflows/consul.aspnetcore.yml
When creating nuget packages, the CI pipeline will use the short commit id as as version suffix. There seems to be an issue when the commit id is purely numeric, and begins with leading zero. To workaround the issue, we use an alphabetic character prefix to convince the packager that our suffix is really a string.
Credits to @MoFtZ who fixed it in [ILGPU](https://github.com/m4rs-mt/ILGPU) in https://github.com/m4rs-mt/ILGPU/pull/340
=> Fix version suffix for unreleased nuget packages

.github/workflows/ci.yml, .github/workflows/consul.aspnetcore.yml
Using a fixed OS version avoids warnings when the `latest` label will soon change, as is the case for `ubuntu-latest` currently. It also ensures more reproducibility in terms of CI.
=> Use fixed OS version in the CI

.github/workflows/ci.yml
A condition is added to the `check-format` CI job to prevent it from running twice when a PR is opened from a branch in the same repo. This makes it aligned to what we do for the `build` job.
=> Run the check-format job only once per PR

.github/workflows/ci.yml, .github/workflows/consul.aspnetcore.yml
This PR fixes the publication of the `Consul.AspNetCore` NuGet package by making the shell do the globbing to find the package, like we already did for the main package. As there was no reason to publish the package with Windows specifically, we switch both publication jobs to Linux, which uses `bash` by default.
=> Fix Consul.AspNetCore NuGet package publication

Consul.Test/AgentTest.cs
By default the `ContinueWith` runs the continuation regardless of the reason for completing the preceding task, whether it completed normally or was cancelled via cancellation token. As a result even when `logsTask` completed sooner, the `timeoutTask` was completing immediately after it due to usage of cancellation token. It was a race condition, because `Task.WhenAny` could select either task.
After this change there is no race condition anymore.
=> Fix the flakiness of Agent_Monitor test

Consul.Test/EventTest.cs
Fixes the flakiness of the `Event_FireList` by usage of Consul blocking queries feature.
=> Fix the flakiness of the Event_FireList test by using blocking queries

Consul.Test/AgentTest.cs, Consul/Lock.cs, Consul/Semaphore.cs
The logic for calculating the `WaitTime` was broken.
I think that this bug was inherited from go library. It is fixed there already (https://github.com/hashicorp/consul/commit/9043966efdab6e8e12c73772de070e25c4a50bc1)
=> Fix lock and semaphore timeouts

.github/workflows/ci.yml, Consul/Consul.csproj
Fixes the https://github.com/G-Research/consuldotnet/issues/69
Before this change the `Newtonsoft.Json` dependency was merged into the main `consul` assembly only in the CI pipeline but not when it was built locally. After this change the merge step will run for all local builds so there is no need to run in in the CI pipeline anymore. It is alternative approach to the one proposed in the https://github.com/G-Research/consuldotnet/pull/71.
=> Merge Newtonsoft.Json at build time

nuget.config
This PR ~~deletes the obsolete `NuGet.config` file that was adding the `dotnet-core` feed from myget.org~~ removes the obsolete `dotnet-core` feed from myget.org from the `NuGet.config` file.
This fixes recent CI issues like this one: https://github.com/G-Research/consuldotnet/pull/70/checks?check_run_id=2203971524.
~~It also resets the NuGet sources on Windows runners to workaround an issue where `dotnet restore` can [sometimes fail](https://github.com/G-Research/consuldotnet/runs/2204304465).~~
=> Fix recent CI issues

Consul.Test/FilterTests.cs, Consul/Client.cs, Consul/Client_GetRequests.cs, Consul/Filtering/Constraints.cs, Consul/Filtering/Filter.cs, Consul/Filtering/Filters.cs, Consul/Filtering/IEncodable.cs, Consul/Filtering/Selectors/MetaSelector.cs, Consul/Filtering/Selectors/NodeSelector.cs, Consul/Filtering/Selectors/Selector.cs, Consul/Filtering/Selectors/Selectors.cs, Consul/Filtering/Selectors/ServiceMetaEntrySelector.cs, Consul/Filtering/Selectors/ServiceSelector.cs, Consul/Filtering/Selectors/StringFieldSelector.cs, Consul/Filtering/Selectors/TagsSelector.cs, Consul/Health.cs, Consul/Interfaces/IHealthEndpoint.cs
Added [server-side filtering support](https://www.consul.io/api-docs/features/filtering) as an eDSL
This implementation supports filtering by the following components:
- Service
- ID
- Tags
- Meta
With the following operations:
- and
- or
- not
- ==
- !=
- contains
- is empty
For Health.Service
whenever they are applicable to the listed components
Functionally satisfies #26
=> Added service and node filtering abilities into QueryOptions

Consul.Test/SemaphoreTest.cs, Consul/Lock.cs
Fixes part of https://github.com/G-Research/consuldotnet/issues/65 (should be split in 2 issues).
This resulted in a NullReferenceException hiding the expected (?) LockNotHeldException.
=> Lock: Add missing null check

Consul.Test/SemaphoreTest.cs, Consul/Lock.cs
This is based on https://github.com/G-Research/consuldotnet/pull/66 for now, otherwise it throws the null ref as well. 
So once https://github.com/G-Research/consuldotnet/pull/66 is merged, I will rebase and cleanup this.
Partial fix for https://github.com/G-Research/consuldotnet/issues/65
=> Lock: Forward user cancellation token downstream

Consul/Session.cs
This was causing token destruction to fail when a per-request ACL token is used.
=> Pass WriteOptions parameter to correct parameter of Put(...)

Consul/Agent.cs, Consul/AuthMethod.cs, Consul/Client.cs, Consul/KV.cs, Consul/Session.cs
Optional argument after generic argument can lead to mistakes, e.g. https://github.com/G-Research/consuldotnet/pull/76.
It is better to make the internal API less ambiguous to avoid such mistakes in the future.
=> Make the internal API less ambiguous

.github/workflows/ci.yml, CHANGELOG.md, Consul.AspNetCore/Consul.AspNetCore.csproj, Consul/Consul.csproj, README.md
- I've run `git log --pretty=oneline v1.6.1.1..master` to see what changes were made since last release.
- ~~I've-- switched from `VersionPrefix` to `Version` as we want to be able to specify pre-release version (with pre-release suffix)~~
- Updated Consul from `v1.6.1` to `v1.6.10`
=> Prepare for a new release - update the changelog and version

.github/workflows/ci.yml
Previously, the script was checking the version of a NuGet package by reading the `VersionPrefix` property from a project file. 
Unfortunately, this approach didn't work when we wanted to use `VersionSuffix` property to define pre-release versions.
With this change we firstly build the NuGet package and only then we compare its actual version and the expected version derived from the tag.
=> Enable publishing pre-release versions

Consul/Consul.csproj
Removing `VersionSuffix`  to make stable release.
I've confirmed the ABI compatibility of versions `1.6.1.1` and `1.6.10.1-rc1` in ways:
- by using [PublicApiGenerator](https://github.com/PublicApiGenerator/PublicApiGenerator)
- by checking out `v1.6.1.1` and referencing version `1.6.10.1-rc1` from the `Consul.Test` and running all tests successfully
=> Remove pre-release suffix

Consul.Test/ACLReplicationTest.cs, Consul.Test/ACLTest.cs, Consul.Test/AgentTest.cs, Consul.Test/AuthMethodTest.cs, Consul.Test/BaseFixture.cs, Consul.Test/CatalogTest.cs, Consul.Test/ClientTest.cs, Consul.Test/CoordinateTest.cs, Consul.Test/EventTest.cs, Consul.Test/FilterTests.cs, Consul.Test/HealthTest.cs, Consul.Test/KVTest.cs, Consul.Test/LockTest.cs, Consul.Test/OperatorTest.cs, Consul.Test/PolicyTest.cs, Consul.Test/PreparedQueryTest.cs, Consul.Test/RoleTest.cs, Consul.Test/SemaphoreTest.cs, Consul.Test/SessionTest.cs, Consul.Test/SnapshotTest.cs, Consul.Test/StatusTest.cs, Consul.Test/TokenTest.cs
sometimes Consul does not initialize fast enough when running parallel tests on the CI. This not elegant workaround aims to address that.
This PR needs to be merged before https://github.com/G-Research/consuldotnet/pull/80
=> Introduce BaseFixture to try to fix intermittent test failures

.github/workflows/ci.yml, Consul.AspNetCore.Test/Consul.AspNetCore.Test.csproj, Consul.AspNetCore/Consul.AspNetCore.csproj, Consul.Test/ClientTest.cs, Consul.Test/Consul.Test.csproj, Consul/Client.cs, Consul/Client_DeleteRequests.cs, Consul/Client_Exceptions.cs, Consul/Client_GetRequests.cs, Consul/Client_Options.cs, Consul/Client_PostRequests.cs, Consul/Client_PutRequests.cs, Consul/Client_Request.cs, Consul/Client_Results.cs, Consul/Consul.csproj, Consul/GlobalSuppressions.cs, Consul/KV.cs, Consul/Lock.cs, Consul/Properties/AssemblyInfo.cs, Consul/Semaphore.cs, Consul/Session.cs
While reviewing the https://github.com/G-Research/consuldotnet/pull/80, I've realised that we can simplify our project files:
- `AssemblyName` and `PackageId` are automatically inferred from the project file name
- `Generate*` can be replaced with single `GenerateAssemblyInfo`
- There is no need to define `CORECLR` constant because `NETSTANDARD` and `NETCOREAPP` are already available
=> Simplifying project files

Consul/Consul.csproj
This PR enables merging `Newtonsoft.Json` into `Consul` on .NET Framework, even when building with `mono`.
=> Use ILRepack instead of ILMerge so .NET Framework builds the same on all platforms

Consul.Test/BaseFixture.cs, Consul.Test/Consul.Test.csproj
There was a problem with updating `GitHubActionsTestLogger` to latest version because some `.NETFramework` tests were failing.
It turned out that that problem is caused by the value of `ServicePointManager.DefaultConnectionLimit`. If it was too low then some tests were unable to complete successfully as some required HttpConenctions couldn't be established.
Now we can run .NETFramework tests on all OS platforms
=> Update GitHubActionsTestLogger to 1.2.0 & fix HttpConnectionLimit issue

Consul.AspNetCore/Consul.AspNetCore.csproj, Consul/Consul.csproj
Prerequisite to #95.
This should always be done as a post-release action so that preview builds have a higher version than stable builds.
=> Bump version to 1.6.10.2

.github/workflows/ci.yml, README.md
This PR enables publishing preview versions to a separate feed whenever we push to `master`.
Pre-requisites:
We should probably bump the version number (say, to 1.6.10.2) so that any new preview version would get published with a higher version number than our latest stable release.
Fixes #68.
=> Publish preview versions

.github/workflows/ci.yml
Our package publishing steps were broken because no artifact name was provided. This meant that packages got uploaded as `artifact` (the default name), but then all artifacts were downloaded and expanded in the `dist` directory, thus ending up in `dist/artifact/` instead of `dist/`.
This PR fixes that by uploading and downloading with an explicit name, ensuring that the NuGet packages end up in `dist/` in the publishing jobs.
=> Fix package publishing

.github/workflows/ci.yml
Yet another CI fix (hopefully the last today 😅). This one fixes a duplicate push of the preview builds (see [an example of the issue](https://github.com/G-Research/consuldotnet/runs/2914062885#step:3:16) on the latest push to `master`).
I also simplified the publication of release builds, as the package versions get checked earlier in the `package` job.
=> Avoid publishing duplicates

.github/workflows/ci.yml, Consul.AspNetCore.Test/Consul.AspNetCore.Test.csproj, Consul.AspNetCore/Consul.AspNetCore.csproj, Consul.Test/Consul.Test.csproj, Consul/Consul.csproj, Directory.Build.props
No functional change, except for adding `TreatWarningsAsErrors` to local dev and not only CI.
Existing work from https://github.com/G-Research/consuldotnet/pull/80
=> Use directory.build.props to centralize configuration

.github/workflows/ci.yml
This PR fixes some inconsistencies in our use of the latest .NET 5 SDK, whilst also reformatting the CI configuration for style consistency.
=> Use .NET 5 SDK in every CI job

.github/workflows/ci.yml
This PR changes the suffix of preview versions to be `preview-yyyyMMddHHmmss-commitSHA` (e.g. `preview-20210705083815-562c1d5`) so that they are properly ordered on the feed.
=> Change the suffix of preview versions for proper ordering

Consul/ACL.cs, Consul/Agent.cs, Consul/Health.cs, Consul/KV.cs, Consul/Session.cs
Fixes some warnings from the CodeQL "security-and-quality" checks:
> Equals should not apply "as"
> Implementations of 'Equals' should not use "as" to test the type of the argument, but rather call GetType(). This guards against the possibility that the argument type will be subclassed. Otherwise, it is likely that the Equals method will not be symmetric, violating its contract."
=> Fix the equality check

.github/workflows/ci.yml
This PR updates (once again) the Consul agent versions to the latest ones available.
I will open another PR to add testing against Consul 1.11.x, as it requires some changes in our unit tests.
=> Update Consul agent versions used for testing

.github/workflows/ci.yml
Fixes https://github.com/G-Research/consuldotnet/runs/5330947266?check_suite_focus=true
=> CI: Pin .NET SDK 6.0.102 for now to avoid dotnet format regression

.github/workflows/scripts/update-consul-versions.ps1, .github/workflows/update-consul-versions.yml
This PR introduces a new daily scheduled workflow that checks for the latest versions of Consul and updates our CI with them if needed. It will do so by creating a new branch with the changes and opening a PR, which is much better than me doing all of that manually every once in a while 😅
As the default token used by GitHub Actions does not have the special `workflows` permissions required to update our CI, a custom GitHub App had to be created instead with the required permissions. Its credentials have been set as secrets within the `update-consul-versions` environment that only `master` can access.
An example of a PR created by this workflow can be found here: https://github.com/jgiannuzzi/consuldotnet/pull/2
=> Auto-update Consul versions

.github/workflows/ci.yml
Now that https://github.com/dotnet/format/issues/1519 has been solved (in .NET SDK 6.0.202), we can revert the pinning.
=> CI: Revert .NET SDK pinning for dotnet format

Consul.AspNetCore/Consul.AspNetCore.csproj, Consul/Agent.cs, Consul/AuthMethod.cs, Consul/Consul.csproj, Consul/KV.cs, Consul/PreparedQuery.cs
Follows up the user report from #146. By adding Roslyn analyser to the Consul project we prevent from similar issues happening ever again.
PS:
I've found a nice write up about the ConfigureAwait issue https://devblogs.microsoft.com/dotnet/configureawait-faq/ (TLDR: in the library code should use `ConfigureAwait(false)` to avoid some deadlock scenarios)
=> Enforce `ConfigureAwait(false)` on the whole library

Directory.Build.props
Version 1.6.10.6 was just published, so we should bump version for preview builds
=> Bump patch version for preview builds

CHANGELOG.md, Consul.Test/AgentTest.cs, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
Consul docs about parameter: https://www.consul.io/api-docs/agent/service#replace-existing-checks
It was added in Consul v1.6.1, but not presented in this library
=> Add support for replace-existing-checks parameter

Consul.Test/TokenTest.cs
Fixes: #165 
The test was relying on the order of elements returned in the response. I don't think there is any reason to do it.
=> Fix the indeterministic failures in Token_CreateWithServiceIdentitiesDelete test

.github/workflows/nudge.yml
@jgiannuzzi This PR introduces a workflow that will be triggered when CI and CodeQL workflows are completed. By default, you will receive a notification in Slack only if they had failed.
[Here](https://github.com/pavlovic-ivan/consuldotnet/actions/runs/3275997830) is the CI workflow that failed. And [here](https://github.com/pavlovic-ivan/consuldotnet/actions/runs/3276267169) is the workflow that got triggered, that had sent the notification to Slack.
In this PR, when the Github Action Octo Nudge is callled, it is using default values. In short:
- notify if workflow conclusion is failure
- notify if a workflow is triggered by a push or schedule to the master branch
You can check the rest [here](https://github.com/pavlovic-ivan/octo-nudge#action-input-arguments).
I've tested using my fork, …
=> Add octo nudge workflow. Trigger on CI and CodeQL workflows

Consul.Test/AgentTest.cs, Consul/Agent.cs
Fixes https://github.com/G-Research/consuldotnet/issues/184
Apparently, the [documentation about checks](https://developer.hashicorp.com/consul/api-docs/agent/check#json-request-body-schema) is incorrect. To specify the id of a check we need to use `CheckId` instead of `ID` parameter. I'm also adding a corresponding test so we have proof that it actually works.
=> Add CheckId to the AgentServiceCheck and mark the ID as obsolete

Directory.Build.props
We've just released version 1.6.10.8. Now, as a final post-release step we need to bump the minor version.
=> Bump the version

.gitpod.Dockerfile, .gitpod.yml
- Installing .NET SDK, Consul Server and Mono during custom Docker image build.
- Running Consul Server on startup.
- Configuring GitHub integration, pre-builds.
- Adding C# extension to VS Code.
=> Adding GitPod

CONTRIBUTING.md, README.md
- adding GitPod button to CONTRIBUTING.md guide.
- adding badges to README.md.
=> adding Badges

Directory.Build.props
We've recently published a https://consuldot.net website.
=> Updating project URL

.config/dotnet-tools.json, .github/workflows/ci.yml, Consul.AspNetCore.Test/Consul.AspNetCore.Test.csproj, Consul.Test/Consul.Test.csproj, global.json
- Ubuntu-18.04 is deprecated ( "The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023" - https://github.com/actions/runner-images/issues/6002). I think we should use "latest" images for all systems. Either "latest" or "fixed" images are being updated continuously, so I don't think there is a benefit of using a "fixed" version.
- netcoreapp2.1 and netcoreapp3.1 are now a [history](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle), I think it is enough to test the last three official releases.
- we need to use `dotnet-format` instead of `dotnet format` due to pending issues with the latter (https://github.com/dotnet/format/issues/1500, https://github.com/dotnet/format/issues/1560)
=> Update CI, drop tests for old frameworks, add net7.0

Consul.Test/AgentTest.cs, Consul.Test/ServiceKindUnitTests.cs, Consul/Agent.cs
Added basic Consul Connect support when registering service on agent.
https://developer.hashicorp.com/consul/docs/connect/registration/sidecar-service
=> Basic Connect support for service registration on the agent

Consul.Test/AgentTest.cs, Consul.Test/FilterTests.cs, Consul/Agent.cs, Consul/Filtering/Selectors/Selectors.cs, Consul/Filtering/Selectors/ServiceSelector.cs, Consul/Interfaces/IAgentEndpoint.cs
class Selectors:
Add Property ServiceName
class ServiceSelector:
Add operator ==
Add operator !=
Add Tests
class Agent:
Add method Checks with filter
Add Tests
=> Adding features

.github/workflows/ci.yml, Consul.Test/ACLTest.cs, Consul.Test/BaseFixture.cs, Consul.Test/Consul.Test.csproj, Consul.Test/OperatorTest.cs
This PR:
1. Fixes version parsing by using a class that properly understands semantic versioning (e.g. version `1.6.10+ent`)
2. We run Enterprise tests on all branches. 
3. We don't have the license environment variable set yet, but it turns out that older versions of Consul can be run anyway.
=> Unblock the CI for enterprise version

Consul.Test/AgentTest.cs, Consul.Test/ClientTest.cs, Consul/Catalog.cs, Consul/Client_GetRequests.cs, Consul/Client_Options.cs, Consul/Client_Results.cs, Consul/Interfaces/ICatalogEndpoint.cs, Consul/Lock.cs
Closes https://github.com/G-Research/consuldotnet/issues/142.
- Add support for agent cache
- Applied some lint suggestions
- Add test for agent cache
- Add test for setting agent cache
=> feat: add support for agent cache

.github/workflows/ci.yml
Fixes problem with the missing consul license secret, when the PR is created from a fork.
=> Enterprise tests running on a PR from fork 

Consul.Test/BaseFixture.cs, Consul.Test/NamespaceTest.cs, Consul/Client.cs, Consul/Client_DeleteRequests.cs, Consul/Client_GetRequests.cs, Consul/Client_Options.cs, Consul/Client_PostRequests.cs, Consul/Client_PutRequests.cs, Consul/Client_Request.cs, Consul/Interfaces/INamespacesEndpoint.cs, Consul/Namespace.cs, docs/docs/2-guides/1-basic-usage.mdx, docs/docs/2-guides/3-supported-apis.mdx
- Add v1.7 Enterprise-only `Namespace`
- Apply lint suggestions
=> feat: introduce `Namespace`

Consul/Namespace.cs
- Reuse implemented methods on overloads
No idea why I didn't write it like this originally.
=> refactor: reuse already implemented methods in Namespaces

Consul.Test/KVTest.cs, Consul/KV.cs
- Closes #138
- Add unit test for this issue
- Apply minor lint changes
=> fix: write correct value for KV.Release

Consul.Test/HealthTest.cs, Consul/Health.cs
Fixes https://github.com/G-Research/consuldotnet/issues/242
=> Add ServiceTags to the health check endpoint

CHANGELOG.md, Directory.Build.props
See the workflow failure(https://github.com/G-Research/consuldotnet/actions/runs/6580074725/job/17877720857), version `1.7.14.0` cannot be really created with NuGet as `1.7.14.0 ` and `1.7.14` are equivalent and NuGet chooses to create a 3-number version.
=> For the 4-number version we cannot use 0 as the last component.

Consul.Test/AgentTest.cs, Consul/Agent.cs, Consul/Client_GetRequests.cs, Consul/Health.cs, Consul/Interfaces/IAgentEndpoint.cs
- Closes #25
- Implementing the latest v1.16 of `/agent/health/service`
=> feat: implement local service health check

Consul.Test/AgentTest.cs, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
Fixes https://github.com/G-Research/consuldotnet/issues/262
@marcin-krystianc  @naskio
=> Added support for Agent Metrics

Consul.Test/AgentTest.cs, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
fixes https://github.com/G-Research/consuldotnet/issues/258
@marcin-krystianc @naskio
=> Added support for agent host

Consul.Test/ConfigurationTest.cs, Consul/Configuration.cs, Consul/Interfaces/IConfigurationEndpoint.cs
Fixes https://github.com/G-Research/consuldotnet/issues/270
=> Support Listing and Deleting Configuration Entries

Consul.Test/CatalogTest.cs, Consul.Test/test_config.json, Consul/Catalog.cs, Consul/Interfaces/ICatalogEndpoint.cs
fixes #272
@marcin-krystianc @naskio
=> Support for Listing Services for Node and Retrieving Nodes that support Mesh Capable Service

.github/workflows/ci.yml, Consul.Test/AgentTest.cs, Consul.Test/Consul.Test.csproj, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
Fixes https://github.com/G-Research/consuldotnet/issues/264
@marcin-krystianc @naskio
=> Added Test for Reload

Consul.Test/AgentTest.cs, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
fixes https://github.com/G-Research/consuldotnet/issues/260
@marcin-krystianc  @naskio
=> Added support for agent version

docs/docs/3-contributing/6-release-process.mdx
-adding "Updating Documentation" section to the release process page
=> improve Documentation

Consul/Interfaces/IConsulClient.cs
The Configuration endpoint cannot be used in DI because the Configuration property is not declared in the IConsulClient interface.
=> Add the Configuration property to the IConsulClient interface

.github/workflows/ci.yml, CHANGELOG.md, Consul.AspNetCore.Test/Consul.AspNetCore.Test.csproj, Consul.Test/Consul.Test.csproj, global.json
Since `net5.0` is long out of support and the `macos-latest` now points to arm64 macos runners, which only support .NET 6 and above, we fix it by:
- removing tests for `net5.0` and adding `net8.0` instead
- removing workaround for `net461` (workaround is not needed anymore)
=> Fix macOS net5.0 failures

.github/workflows/deploy-website.yml, Consul.Test/HealthTest.cs, Consul/Health.cs, Consul/Interfaces/IHealthEndpoint.cs
1. Added GET /health/connect/:service into `Health.cs`
2. Included new endpoints into `IHealthEndpoint.cs`
Refers to issue #311
=> Added list nodes for connect-capable service with endpoints

.github/dependabot.yaml, .github/workflows/nudge.yml, .github/workflows/update-consul-versions.yml
CI: Resolve deprecation & warning messages in workflows 
Enable DependaBot for GitHub actions
Node16 has been out of support since [September 2023](https://github.com/nodejs/Release/#end-of-life-releases). - more info in the [post](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/) 
- Remove `dependabot.yaml` as `dependabot.yml` is only one needed 
- Bump the steps where deprecation/warnings are shown in the job
- Fix `set-output` warnings in workflows 
__Optional__
- Resolve on upstream or find alternative for `technote-space/create-pr-action@v2` used in [Update consul versions](https://github.com/G-Research/consuldotnet/actions/runs/8197862332) workflow
https://github.com/G-Research/gr-oss/issues/636
------------
**CI** …
=> CI: Fix warnings & deprecation messages in the workflows

.github/workflows/ci.yml, Consul.Test/AgentTest.cs, Consul.Test/test_config.json, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
1. Added GET /v1/agent/connect/ca/roots endpoint
2. Included new endpoint into ICatalogEndpoint.cs
3. Added possible test to AgentTest.cs
4. Edited test_config.json for the test
*  Refers to issue https://github.com/G-Research/consuldotnet/issues/331
=> Connect CA Roots

.github/workflows/ci.yml
We have a "formatter" workflow that applies automatic code changes. The downside of applying automatic code changes is that they do not trigger other workflows (e.g., the "CI" workflow). To work around this problem, we can enable manual workflow runs.
=> [CI] Enable manual CI runs

Consul.Test/AgentTest.cs, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
=> Added GetCALeaf endpoint, added tests for the endpoint in AgentTest.cs, modified IAgentEndpoint.cs to have GetCALeaf

Consul.Test/AgentTest.cs, Consul/Agent.cs, Consul/Interfaces/IAgentEndpoint.cs
=> Added POST ConnectAuthorize endpoint, added test for the endpoint, method to IAgendEndpoint.cs

Consul.Test/HealthTest.cs
`Health_Connect` failed from time to time,
It seems that the "connect" related information is not immediately updated. Hence we need to refer to blocking queries (i.e. set the `waitindex >0`).
=> Fixing flaky Health_Connect test

.github/workflows/ci.yml, Consul/ACL.cs, Consul/Agent.cs, Consul/Catalog.cs, Consul/Client_Request.cs, Consul/Configuration.cs, Consul/Coordinate.cs, Consul/Event.cs, Consul/Health.cs, Consul/KV.cs, Consul/Lock.cs, Consul/Raw.cs, Consul/Session.cs, Directory.Build.props
Without `GenerateDocumentationFile` set to true, your great code summaries never make it to the developer using the nuget.
=> Add GenerateDocumentationFile to make summaries show up in IDEs

Consul.Test/PreparedQueryTest.cs, Consul/Interfaces/IPreparedQueryEndpoint.cs, Consul/PreparedQuery.cs
Add support for Explain Prepared Query API endpoint in Consul.Net (implementation only, tests pending)
#367 
@naskio
=> feat: add support for explain prepared query API endpoint

Consul.Test/OperatorTest.cs, Consul/Interfaces/IOperatorEndpoint.cs, Consul/Operator.cs
Added support for List segments Endpoint #373
=> add support for list segments endpoint

Consul.Test/ConfigurationTest.cs
Recently, there was a change in consul in the validation of the `protocol` field -> https://github.com/hashicorp/consul/blame/2618fc1bd9894f97a71e2040516bbe21e3d9fecd/agent/structs/config_entry.go#L271-L276 which causes our tests to fail with:
``` 
invalid value for protocol: https
```
=> Fixing tests for configuration endpoint

docs/docusaurus.config.js
This PR add search input to the website header (using Algolia DocSearch)
=> add search to website

.github/workflows/deploy-website.yml, docs/docusaurus.config.js
This PR optimizes the CI/CD workflow for the documentation website:
- Skips deployment steps if GitHub Pages is disabled or the branch is not the default
- Uses `yarn` consistently instead of detecting the package manager
- Updates to the latest Node LTS version
- Adds a more realistic fallback tag for deployment versioning
- Constrains only the deploy job concurrency
- Triggers the workflow only on changes to the `docs/` folder (on push or on pull_request)
- Dynamically set url and baseUrl to allow deploying in forks (for example: https://naskio.github.io/consuldotnet/)
=> Improve CI/CD for documentation website

Consul.Test/ClientTest.cs, Consul/Client.cs
Restore default port 8500 for CONSUL_HTTP_ADDR when no port is specif…ied (#394)
=> restore default port 8500 for CONSUL_HTTP_ADDR (#394)

Consul.Test/ClientTest.cs, Consul/Client.cs
Fix for consul address parsing for cases like:`my.consul.com:5678`, `http://my.consul.com:5678`, `my.consul.com` 
fixes https://github.com/G-Research/consuldotnet/issues/359
=> Fix parsing the string based host name

Consul.sln, Directory.Build.props, nuget.config
=> Embed PDBs

.github/workflows/ci.yml, .github/workflows/nudge.yml, Consul.AspNetCore.Test/Consul.AspNetCore.Test.csproj, Consul.Test/BaseFixture.cs, Consul.Test/Consul.Test.csproj, Directory.Build.props, global.json
- `.NET 8` is the latest LTS
- `.NET 9` is the latest STS (Standard Term Support)
- `.NET 6` and `.NET 7` are out of support
- taking out the `macos-13` from the matrix and adding a single job with it to reduce matrix cardinality
=> [CI] Update .NET versions and reduce test matrix cardinality

.github/workflows/ci.yml, Consul.Test/ConnectTest.cs
Our updater resurrects version 1.6.10 -> https://github.com/G-Research/consuldotnet/pull/385
I think it makes more sense to add version 1.6 to the test pool instead of changing the updater to avoid re-adding that version.
Additionally, I think it makes sense to reduce the cardinality of our test matrix (see https://github.com/G-Research/consuldotnet/pull/416)
=> Unblocking consul agent versions updater

Consul.Test/ConnectTest.cs, Consul/Connect.cs, Consul/Interfaces/IConnectEndpoint.cs
This PR adds supports to [Read Specific Intention By Name](https://developer.hashicorp.com/consul/api-docs/v1.11.x/connect/intentions#read-specific-intention-by-name)
=> Read Specific Intention By Name

Consul.Test/OperatorTest.cs, Consul/Interfaces/IOperatorEndpoint.cs, Consul/Operator.cs
This pull request implements the `GET /v1/operator/autopilot/configuration` endpoint under the `Operator` client and adds initial test coverage for it. 
The following changes were made:
- Introduced `AutopilotConfiguration` model to represent the returned configuration structure.
- Implemented `Operator.AutopilotGetConfiguration` method with support for optional query parameters.
- Included a unit test verifying that the method returns valid configuration and query metadata.
Additional test cases (e.g., with query options, stale reads, serialization checks) will be submitted in a follow-up commits.
Closes #475
The implementation follows the style and structure of other operator endpoints in the codebase. The test was added to the `OperatorTest` class and uses the shared `_client` instance …
=> Retrieve the current Autopilot configuration

Consul.Test/OperatorTest.cs, Consul/Interfaces/IOperatorEndpoint.cs, Consul/Operator.cs
[FEATURE]: Read autopilot health `GET /v1/operator/autopilot/health`
This PR introduces full support for the `GET /v1/operator/autopilot/health` endpoint in Consul.NET. It includes:
- Added `AutopilotHealth` and `AutopilotServerHealth` classes to represent the response payload.
- Implemented `AutopilotGetHealth` method to handle the API call.
- Updated `IOperatorEndpoint` to expose the new methods.
- Added test to verify endpoint correctness.
Fixes #477
The implementation follows the structure used in other Operator endpoint integrations for consistency. Refer to doc: [Link to Reference Doc](https://developer.hashicorp.com/consul/api-docs/operator/autopilot#read-health)
=> Read autopilot health

Consul.Test/OperatorTest.cs, Consul/Interfaces/IOperatorEndpoint.cs, Consul/Operator.cs
This PR adds support for the Consul Operator Autopilot Configuration API endpoint  
(**PUT /v1/operator/autopilot/configuration**), which allows updating the Autopilot configuration of a Consul cluster.
- Added `AutopilotSetConfiguration()` method with both default and `WriteOptions` overloads
- Updated the `IOperatorEndpoint` interface with the new method signatures
- Added unit test to verify functionality
Implements: [Autopilot API – Update Autopilot Configuration](https://developer.hashicorp.com/consul/api-docs/operator/autopilot#update-configuration)
Closes: #485
=> [FEATURE]: Add support for PUT /v1/operator/autopilot/configuration

.github/workflows/ci.yml
Recent macOS runners are missing mono installation.
=> Set up mono on macOS runners
